### ISSUE TITLE
INVALID_STATE_ERR

### ISSUE THREAD

**Issue by ManjuSagar** [tiaanduplessis/react-native-websocket#1]
Socket is opening but when i send the data i am getting this error. 

 I am using this below versions
   react-native = 0.43.4
   react-native-websocket = 1.0.0

**Comment by ManjuSagar** [comment]
i was sending the event outside of onopen. Mistake from my side.

**Comment by tiaanduplessis** [comment]
No problem. Glad you got it solved 👍

**Comment by quantumproducer** [comment]
Why is this a problem?
On Desktop, I can call .send outside of .onopen

**Comment by griimick** [comment]
Same. Why is this a problem. On Desktop, I can call .send outside of .onopen

**Comment by ththugues44** [comment]
@griimick @quantumproducer @tiaanduplessis please  how to send a message to the server outside the WS component ?

**Comment by griimick** [comment]
@ththugues44 Check out the [usage example](https://github.com/tiaanduplessis/react-native-websocket#usage). You can use the ref to access the class methods defined in the WS component outside the component.  [React Refs reference](https://reactjs.org/docs/refs-and-the-dom.html)
