### ISSUE TITLE
Consider deleting

### ISSUE THREAD

**Issue by maxmcd** [tiaanduplessis/react-native-websocket#6]
I mean this in (I hope) the most constructive way. This repo is misleading and should be deleted.

 - It's a very very thin wrapper around  networking functionality that ships with react native. 
 - It arguably misuses a react component to handle dynamic functionality
 - It implements irresponsible reconnect logic. (If someone actually shipped this component and their ws server momentarily went down they would be hammered with requests)

This repo is currently the 2nd google result for "react-native websockets". At the risk of a new user getting the wrong impression about quite a lot of things I'd like to cast a vote for either deleting this project or adding a detailed disclaimer.

**Comment by tiaanduplessis** [comment]
Hi @maxmcd. I'm more than willing to accept a PR to add a disclaimer as requested. I will also consider renaming it, as npm doesn't really allow me to delete completely. The current name is a bit too generic and could be misleading.
